# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 492b27063ab3cb789a66ba1d944baab232013419847721c7d3122b6ac39795e0d48a1d50bed582a8eedbf083d458d2e60be98fac24a770295287ed45590f7a8a

test:
  secret_key_base: 4fd53b49190f5dcc78872aff02ee8a4e3c215a974e4a2f1c5f503e8fd607050005bea21c1437318bea02ae6c9bb27e3dac0060d5b1fa89385a6362bf7621745c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
